trigger:
  branches:
    include:
      - main  # Triggers pipeline on code push to the main branch

pool:
  vmImage: 'windows-latest'  # Use a Microsoft-hosted agent

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'  # Specify the .NET version

  - script: dotnet restore
    displayName: 'Restore NuGet Packages'  # Restores dependencies

  - script: dotnet build --configuration Release
    displayName: 'Build the Solution'  # Compiles the code

  - script: dotnet test --configuration Release
    displayName: 'Run Unit Tests'  # Runs automated tests

  - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
    displayName: 'Publish Build Artifacts'  # Creates deployment-ready files

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Save Artifacts for Deployment'
